apiVersion: v1
kind: PersistentVolume
metadata:
  name: sql-pv
  namespace: mastoura-tawazun
  labels:
    type: local
    app: sql
    name: Mastoura
spec:
  #storageClassName: local-path
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"